

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAMES ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAMES ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findemsdk-demo-pkg.cmake")
# Global approach
set(emsdk-demo-pkg_FOUND 1)
set(emsdk-demo-pkg_VERSION "0.1")

find_package_handle_standard_args(emsdk-demo-pkg REQUIRED_VARS
                                  emsdk-demo-pkg_VERSION VERSION_VAR emsdk-demo-pkg_VERSION)
mark_as_advanced(emsdk-demo-pkg_FOUND emsdk-demo-pkg_VERSION)


set(emsdk-demo-pkg_INCLUDE_DIRS )
set(emsdk-demo-pkg_INCLUDE_DIR "")
set(emsdk-demo-pkg_INCLUDES )
set(emsdk-demo-pkg_RES_DIRS )
set(emsdk-demo-pkg_DEFINITIONS )
set(emsdk-demo-pkg_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(emsdk-demo-pkg_COMPILE_DEFINITIONS )
set(emsdk-demo-pkg_COMPILE_OPTIONS_LIST "" "")
set(emsdk-demo-pkg_COMPILE_OPTIONS_C "")
set(emsdk-demo-pkg_COMPILE_OPTIONS_CXX "")
set(emsdk-demo-pkg_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(emsdk-demo-pkg_LIBRARIES "") # Will be filled later
set(emsdk-demo-pkg_LIBS "") # Same as emsdk-demo-pkg_LIBRARIES
set(emsdk-demo-pkg_SYSTEM_LIBS )
set(emsdk-demo-pkg_FRAMEWORK_DIRS )
set(emsdk-demo-pkg_FRAMEWORKS )
set(emsdk-demo-pkg_FRAMEWORKS_FOUND "") # Will be filled later
set(emsdk-demo-pkg_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(emsdk-demo-pkg_FRAMEWORKS_FOUND "${emsdk-demo-pkg_FRAMEWORKS}" "${emsdk-demo-pkg_FRAMEWORK_DIRS}")

mark_as_advanced(emsdk-demo-pkg_INCLUDE_DIRS
                 emsdk-demo-pkg_INCLUDE_DIR
                 emsdk-demo-pkg_INCLUDES
                 emsdk-demo-pkg_DEFINITIONS
                 emsdk-demo-pkg_LINKER_FLAGS_LIST
                 emsdk-demo-pkg_COMPILE_DEFINITIONS
                 emsdk-demo-pkg_COMPILE_OPTIONS_LIST
                 emsdk-demo-pkg_LIBRARIES
                 emsdk-demo-pkg_LIBS
                 emsdk-demo-pkg_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to emsdk-demo-pkg_LIBS and emsdk-demo-pkg_LIBRARY_LIST
set(emsdk-demo-pkg_LIBRARY_LIST )
set(emsdk-demo-pkg_LIB_DIRS )

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_emsdk-demo-pkg_DEPENDENCIES "${emsdk-demo-pkg_FRAMEWORKS_FOUND} ${emsdk-demo-pkg_SYSTEM_LIBS} ZLIB::ZLIB")

conan_package_library_targets("${emsdk-demo-pkg_LIBRARY_LIST}"  # libraries
                              "${emsdk-demo-pkg_LIB_DIRS}"      # package_libdir
                              "${_emsdk-demo-pkg_DEPENDENCIES}"  # deps
                              emsdk-demo-pkg_LIBRARIES            # out_libraries
                              emsdk-demo-pkg_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "emsdk-demo-pkg")                                      # package_name

set(emsdk-demo-pkg_LIBS ${emsdk-demo-pkg_LIBRARIES})

foreach(_FRAMEWORK ${emsdk-demo-pkg_FRAMEWORKS_FOUND})
    list(APPEND emsdk-demo-pkg_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND emsdk-demo-pkg_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${emsdk-demo-pkg_SYSTEM_LIBS})
    list(APPEND emsdk-demo-pkg_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND emsdk-demo-pkg_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(emsdk-demo-pkg_LIBRARIES_TARGETS "${emsdk-demo-pkg_LIBRARIES_TARGETS};ZLIB::ZLIB")
set(emsdk-demo-pkg_LIBRARIES "${emsdk-demo-pkg_LIBRARIES};ZLIB::ZLIB")

set(CMAKE_MODULE_PATH "/home/bam4d/.conan/data/emsdk-demo-pkg/0.1/_/_/package/435eb98fc958d31ee0d4b24dfea958a386fd922c/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/home/bam4d/.conan/data/emsdk-demo-pkg/0.1/_/_/package/435eb98fc958d31ee0d4b24dfea958a386fd922c/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET emsdk-demo-pkg::emsdk-demo-pkg)
        add_library(emsdk-demo-pkg::emsdk-demo-pkg INTERFACE IMPORTED)
        if(emsdk-demo-pkg_INCLUDE_DIRS)
            set_target_properties(emsdk-demo-pkg::emsdk-demo-pkg PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${emsdk-demo-pkg_INCLUDE_DIRS}")
        endif()
        set_property(TARGET emsdk-demo-pkg::emsdk-demo-pkg PROPERTY INTERFACE_LINK_LIBRARIES
                     "${emsdk-demo-pkg_LIBRARIES_TARGETS};${emsdk-demo-pkg_LINKER_FLAGS_LIST}")
        set_property(TARGET emsdk-demo-pkg::emsdk-demo-pkg PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${emsdk-demo-pkg_COMPILE_DEFINITIONS})
        set_property(TARGET emsdk-demo-pkg::emsdk-demo-pkg PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${emsdk-demo-pkg_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT ZLIB_FOUND)
            find_dependency(ZLIB REQUIRED)
        else()
            message(STATUS "Dependency ZLIB already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${emsdk-demo-pkg_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
